apiVersion: v1
kind: Pod
metadata:
 name: kubernetes-demo-pod
 labels:
   app: demoApp
spec:
 containers:
   - name: kubernetes-demo-container
     image: zxp791228/k8s-flask-demo
     ports:
       - containerPort: 5000 # 要跟flask裡面指定的port一致